server {
    listen 80;

    location / {
        proxy_pass http://app_login:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Importante para que las cookies de JWT fluyan
        proxy_set_header Cookie $http_cookie;
    }

    location /app-swap/ {
        proxy_pass http://app_swap:80/;
        proxy_set_header Host $host;
        proxy_set_header Cookie $http_cookie;
    }

    location /app-tain/ {
        proxy_pass http://app_tain:80/;
        proxy_set_header Host $host;
        proxy_set_header Cookie $http_cookie;
    }
}