# </VirtualHost>
<VirtualHost *:80>
    DocumentRoot /var/www/html
    
    # 1. Configuración para procesar archivos locales (Login/Menú)
    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex login.php login.html index.php
    </Directory>

    # 2. Proxy para SWAP
    # Cuando el usuario vaya a http://localhost:8086/swap
    ProxyPreserveHost On
    ProxyPass /swap http://app_swap/
    ProxyPassReverse /swap http://app_swap/

    # 3. Proxy para TAIN
    # Cuando el usuario vaya a http://localhost:8086/tain
    ProxyPass /tain http://app_tain/
    ProxyPassReverse /tain http://app_tain/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>