name: Filtro de Calidad Doble (React y PHP)

on:
  push:
    branches:
      - main
      - Gerardo
      - mau
      - "**"
  pull_request:
    branches:
      - main

jobs:
  validar-react-sugo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar codigo
        uses: actions/checkout@v4

      - name: Preparar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Validar SUGO (React)
        working-directory: ./apps/SUGO_
        run: |
          npm install
          npm run build

  validar-php-swap:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar codigo
        uses: actions/checkout@v4

      - name: Preparar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Validar SWAP (PHP)
        working-directory: ./apps/SWAP
        run: |
          composer install
          # Este comando busca errores de sintaxis en todos tus archivos PHP
          find . -name "*.php" -exec php -l {} \;

  enviar-a-produccion:
    # Esta linea es la mas importante: solo corre si AMBAS validaciones pasaron
    needs: [validar-react-sugo, validar-php-swap]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Clonar con Llave Maestra
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MI_LLAVE_MAESTRA }}

      - name: Push al Repo de Produccion
        run: |
          git remote add prod https://github.com/SWAP-RTP/SITEG_PRODUCCION.git
          git push prod main --force
